# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1791ff76278dd61b5a0b43b2a8c94d356e1bd7ba74d601f73204ca54e741dcf996baf779c07e5a51d653a55e02604d4433959041350cf2135fb36cc3c22104e

test:
  secret_key_base: b3f761bb59fdb8b77145144a7399145ab688e1cc47464c53f9a94da9e97e35421fc095022d288432a66c9be16c324907086be834e4e5ac01505c983587aa75fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
